module.exports = [
    { "name": "University of Melbourne" },
    { "name": "Australian National University" },
    { "name": "Bond University" },
    { "name": "Carnegie Mellon University - Australia" },
    { "name": "Australian Catholic University" },
    { "name": "Central Queensland University" },
    { "name": "Charles Darwin University" },
    { "name": "Charles Sturt University	" },
    { "name": "Curtin University" },
    { "name": "Deakin University" },
    { "name": "Edith Cowan University" },
    { "name": "Federation University Australia" },
    { "name": "Flinders University" },
    { "name": "Griffith University" },
    { "name": "James Cook University" },
    { "name": "La Trobe University" },
    { "name": "Macquarie University" },
    { "name": "James Cook University" },
    { "name": "Macquarie University" },
    { "name": "Monash University" },
    { "name": "Murdoch University" },
    { "name": "Queensland University of Technology" },
    { "name": "Royal Melbourne Institute of Technology" },
    { "name": "Southern Cross University" },
    { "name": "Swinburne University of Technology" },
    { "name": "Torrens University Australia" },
    { "name": "University of Adelaide" },
    { "name": "The University of Canberra" },
    { "name": "The University of Divinity" },
    { "name": "University of New England" },
    { "name": "University of New South Wales" },
    { "name": "The University of Newcastle" },
    { "name": "The University of Notre Dame Australia" },
    { "name": "University of Queensland" },
    { "name": "University of South Australia" },
    { "name": "University of Southern Queensland" },
    { "name": "University of the Sunshine Coast" },
    { "name": "University of Sydney" },
    { "name": "University of Tasmania" },
    { "name": "University of Technology, Sydney	" },
    { "name": "The University of Western Australia" },
    { "name": "Western Sydney University" },
    { "name": "University of Wollongong" },
    { "name": "Victoria University" },
];